verbatim:
  cabal-version: 2.2

name: solo
version: 0.1.0.0

dependencies: 
  - base
  - random
  - mwc-random
  - statistics
  - typenums
  - text
  - containers
  - MonadRandom

executable:
  source-dirs: src
  main: GaussianL.hs
